export const demoLlamaParseData = {
  pages: [
    {
      page: 1,
      text: "        ICMYK\n\n                           Comprehensive Review of Published GRE Validity Data\n\n                           The Graduate Record Examinations (GRE\") General Test measures skills that faculty and graduate deans have\n                           consistently said are essential to graduate school success These skills of verbal reasoning quantitative reasoning;\n                           and criticalthinkingand analytical writing are foundational skills for applicants to a U.S. graduate program,\n                           regardless of educational or linguistic background or country of origin.\n                           Although the GRE Program has many studies of the predictive validity of the GRE General Test (which are available\n                           on the GRE website: WW.etsorg/gre), a recent meta-analysis by non-ETS researchers Nathan Kuncel, Sarah\n                           Hezlett and Deniz Ones provides additional positive evidence of the relationship of the GRE General Test to various\n                            graduate school success.   This meta-analysis is important because predictive validity studies are often\n                           criteria of                 variety                 (e.g\"\n                           difficult to conduct for a             of reasons                    insufficient data, test scores or predictors of success that do not\n                                                                  vary greatly across examinees): Compared with earlier research; the Kuncel et\n                                                                                                al. meta-analysis improved on these studies by examining the validity\n           Figure L                        PGRATIONIN                                           of the GRE General Test for multiple disciplines using multiple\n           The criteria                                                                                  measures of success, and by addressing statistical artifacts\n        for success         COMPREHENSIVE                         RESEARCH                               such as range restriction:\n                             EXAM SCORES                          PRODUCTIVITY                           One strength of the Kuncel et al. research is that the\n                                                                                                         meta-analysis analyzed datafrom               large data\n                                                                                                                                                       a very\n                                                                                                                                                      set involving more than 1,753 independent samples\n                             1ST YEAR                                                                              based on a pool of more than 80,000 students\n                           GRADUATE GPA    SUCCESS                                              TIME TO DEGREE     In addition, the study looked at five predictors of\n                                                                                                                                                 success and eight criteria for success_ The predictors\n                                                                                                                  included the three measures of the GRE General Test\n                                                                                                                  (verbal reasoning quantitative reasoning and analytical\n                            OVERALL                                            FACULTY                            reasoning), GRE Subject Test scores and undergraduate\n                           GRADUATE GPA                                                                           grade  average (UGPA): The criteria for success are\n                                                                               RATINGS                             point\n\n j                                         DEGREE                                                        shown in the figure to the left\n                                           ATTAINMENT                                           Each of these criteria can be considered a different dimension\n 1                                                                                              of successful performance in graduate school.\n\n                           Results of the Kuncel et al. study\n 1                         Results from this study show that:\n                            The GRE General Test is a             'generalizably valid predictor offirst-yeargraduate GPA, overall graduate GPA,\n      1                     comprehensive exam scores, publication citation counts and faculty ratings:\n 2 8                        The GRE General Test also correlates positively with degree attainment and research productivity:\n                            The GRE General Test has better predictive validity than undergraduate grades or letters of recommendation:\n 1                          The GRE Subject Tests are better predictors of success than either the GRE General Test or undergraduate GPA\nJi\n87                         This meta-analysis study is important because these results apply across a range of intended academic majors,\n#                          across native speakers of English and nonnative speakers of English; across traditional and nontraditional students\n                           and across master's and doctoral programs.?\n\n                           Kuncel,; N R, Hezlett; $. A and Ones; D. $. (2001). comprehensive meta-analysis of the predictive validity of the Graduate Record Examinations: Implications for graduate student\n                           selection and performarice: Psychological Bulletin, 127 (V), 162-181.\n                           The master's analyses can be found in \"The Validity of the Graduate Record Examination for Master' s and Doctoral Programs: Meta-Analytic Investigation\" by Kuncel, NR, Wee;\n                            Serafin; S_   Hezlett; SA (In press) GRE Research Report: Princeton; NJ: ETS.\n                                          and",
      md: "\nICMYK\n\n# Comprehensive Review of Published GRE Validity Data\n\nThe Graduate Record Examinations (GRE) General Test measures skills that faculty and graduate deans have consistently said are essential to graduate school success. These skills of verbal reasoning, quantitative reasoning, critical thinking, and analytical writing are foundational skills for applicants to a U.S. graduate program, regardless of educational or linguistic background or country of origin.\n\nAlthough the GRE Program has many studies of the predictive validity of the GRE General Test (which are available on the GRE website: www.ets.org/gre), a recent meta-analysis by non-ETS researchers Nathan Kuncel, Sarah Hezlett, and Deniz Ones provides additional positive evidence of the relationship of the GRE General Test to various graduate school success. This meta-analysis is important because predictive validity studies are often difficult to conduct for a variety of reasons (e.g., insufficient data, test scores or predictors of success that do not vary greatly across examinees). Compared with earlier research, the Kuncel et al. meta-analysis improved on these studies by examining the validity of the GRE General Test for multiple disciplines using multiple measures of success, and by addressing statistical artifacts such as range restriction.\n\n# Figure 1\n\nCriteria for success\n\n| COMPREHENSIVE RESEARCH | EXAM SCORES     | PRODUCTIVITY   |\n| ---------------------- | --------------- | -------------- |\n| 1ST YEAR GRADUATE GPA  | SUCCESS         | TIME TO DEGREE |\n| OVERALL GRADUATE GPA   | FACULTY RATINGS |                |\n| DEGREE ATTAINMENT      |                 |                |\n\nEach of these criteria can be considered a different dimension of successful performance in graduate school.\n\n# Results of the Kuncel et al. study\n\n1. The GRE General Test is a generalizably valid predictor of first-year graduate GPA, overall graduate GPA, comprehensive exam scores, publication citation counts, and faculty ratings.\n2. The GRE General Test also correlates positively with degree attainment and research productivity.\n3. The GRE General Test has better predictive validity than undergraduate grades or letters of recommendation.\n4. The GRE Subject Tests are better predictors of success than either the GRE General Test or undergraduate GPA.\n\nThis meta-analysis study is important because these results apply across a range of intended academic majors, across native speakers of English and nonnative speakers of English, across traditional and nontraditional students, and across master's and doctoral programs.\n\nKuncel, N. R., Hezlett, S. A., and Ones, D. J. (2001). Comprehensive meta-analysis of the predictive validity of the Graduate Record Examinations: Implications for graduate student selection and performance. Psychological Bulletin, 127(1), 162-181.\n\nThe master's analyses can be found in \"The Validity of the Graduate Record Examination for Master's and Doctoral Programs: Meta-Analytic Investigation\" by Kuncel, N. R., Wee, S., Serafin, S., Hezlett, S. A. (In press) GRE Research Report: Princeton, NJ: ETS.\n\n",
      images: [
        {
          name: "img_p0_1.png",
          height: 1800,
          width: 1424,
          x: -33.802700000000016,
          y: -36.97198000000003,
          original_width: 1424,
          original_height: 1800,
          ocr: [
            {
              x: 69,
              y: 0,
              w: 138,
              h: 43,
              confidence: 0.7704478411417865,
              text: "ICMYK",
            },
            {
              x: 296,
              y: 141,
              w: 549,
              h: 45,
              confidence: 0.8844754140748002,
              text: "Comprehensive Review of Published GRE",
            },
            {
              x: 854,
              y: 137,
              w: 172,
              h: 48,
              confidence: 0.9523644981726365,
              text: "Validity Data",
            },
            {
              x: 272,
              y: 224,
              w: 316,
              h: 26,
              confidence: 0.9820730156183065,
              text: "The Graduate Record Examinations",
            },
            {
              x: 598,
              y: 221,
              w: 646,
              h: 31,
              confidence: 0.7408544669378303,
              text: '(GRE") General Test measures skills that faculty and graduate deans have',
            },
            {
              x: 271,
              y: 246,
              w: 983,
              h: 37,
              confidence: 0.5928730834923976,
              text: "consistently said are essential to graduate school success These skills of verbal reasoning quantitative reasoning;",
            },
            {
              x: 272,
              y: 280,
              w: 98,
              h: 26,
              confidence: 0.9764734735390788,
              text: "and critical",
            },
            {
              x: 442,
              y: 277,
              w: 740,
              h: 33,
              confidence: 0.6453375851201824,
              text: "and analytical writing are foundational skills for applicants to a U.S. graduate program,",
            },
            {
              x: 267,
              y: 304,
              w: 610,
              h: 37,
              confidence: 0.8763870539070586,
              text: "regardless of educational or linguistic background or country of origin.",
            },
            {
              x: 271,
              y: 348,
              w: 1001,
              h: 33,
              confidence: 0.8163763736383427,
              text: "Although the GRE Program has many studies of the predictive validity of the GRE General Test (which are available",
            },
            {
              x: 272,
              y: 378,
              w: 954,
              h: 30,
              confidence: 0.6349119688718706,
              text: "on the GRE website: WW.etsorg/gre), a recent meta-analysis by non-ETS researchers Nathan Kuncel, Sarah",
            },
            {
              x: 272,
              y: 404,
              w: 1004,
              h: 32,
              confidence: 0.8160885038814489,
              text: "Hezlett and Deniz Ones provides additional positive evidence of the relationship of the GRE General Test to various",
            },
            {
              x: 272,
              y: 436,
              w: 86,
              h: 24,
              confidence: 0.9919191253262086,
              text: "criteria of",
            },
            {
              x: 353,
              y: 429,
              w: 222,
              h: 36,
              confidence: 0.610733927191559,
              text: "graduate school success.",
            },
            {
              x: 586,
              y: 432,
              w: 652,
              h: 32,
              confidence: 0.8944813946678937,
              text: "This meta-analysis is important because predictive validity studies are often",
            },
            {
              x: 272,
              y: 462,
              w: 210,
              h: 26,
              confidence: 0.6503657413423922,
              text: "difficult to conduct for a",
            },
            {
              x: 544,
              y: 464,
              w: 96,
              h: 24,
              confidence: 0.8600874610005136,
              text: "of reasons",
            },
            {
              x: 686,
              y: 462,
              w: 558,
              h: 28,
              confidence: 0.9621554518037292,
              text: "insufficient data, test scores or predictors of success that do not",
            },
            {
              x: 586,
              y: 490,
              w: 678,
              h: 30,
              confidence: 0.5873089456115947,
              text: "vary greatly across examinees): Compared with earlier research; the Kuncel et",
            },
            {
              x: 666,
              y: 520,
              w: 606,
              h: 28,
              confidence: 0.761144820335538,
              text: "al. meta-analysis improved on these studies by examining the validity",
            },
            {
              x: 128,
              y: 552,
              w: 80,
              h: 28,
              confidence: 0.9440990299940033,
              text: "Figure L",
            },
            {
              x: 718,
              y: 548,
              w: 544,
              h: 30,
              confidence: 0.7322997425750764,
              text: "of the GRE General Test for multiple disciplines using multiple",
            },
            {
              x: 128,
              y: 580,
              w: 108,
              h: 24,
              confidence: 0.8791936572053045,
              text: "The criteria",
            },
            {
              x: 453,
              y: 573,
              w: 90,
              h: 36,
              confidence: 0.3357480249453726,
              text: "PGRATIONIN",
            },
            {
              x: 751,
              y: 573,
              w: 509,
              h: 33,
              confidence: 0.7461364641139101,
              text: "measures of success, and by addressing statistical artifacts",
            },
            {
              x: 126,
              y: 606,
              w: 110,
              h: 26,
              confidence: 0.9576022814026957,
              text: "for success",
            },
            {
              x: 768,
              y: 602,
              w: 220,
              h: 32,
              confidence: 0.8580483186079778,
              text: "such as range restriction:",
            },
            {
              x: 293,
              y: 627,
              w: 114,
              h: 18,
              confidence: 0.9914585068302261,
              text: "COMPREHENSIVE",
            },
            {
              x: 619,
              y: 621,
              w: 72,
              h: 18,
              confidence: 0.9995586821561997,
              text: "RESEARCH",
            },
            {
              x: 607,
              y: 639,
              w: 94,
              h: 16,
              confidence: 0.8232780538967773,
              text: "PRODUCTIVITY",
            },
            {
              x: 303,
              y: 647,
              w: 96,
              h: 16,
              confidence: 0.9999558973562236,
              text: "EXAM SCORES",
            },
            {
              x: 790,
              y: 645,
              w: 460,
              h: 31,
              confidence: 0.8667713415022541,
              text: "One strength of the Kuncel et al. research is that the",
            },
            {
              x: 798,
              y: 673,
              w: 248,
              h: 30,
              confidence: 0.8449277672140915,
              text: "meta-analysis analyzed data",
            },
            {
              x: 1094,
              y: 678,
              w: 56,
              h: 24,
              confidence: 0.6354458272715865,
              text: "a very",
            },
            {
              x: 1146,
              y: 674,
              w: 94,
              h: 31,
              confidence: 0.9948432405182345,
              text: "large data",
            },
            {
              x: 806,
              y: 700,
              w: 460,
              h: 32,
              confidence: 0.5993061012716224,
              text: "set involving more than 1,753 independent samples",
            },
            {
              x: 810,
              y: 730,
              w: 418,
              h: 28,
              confidence: 0.8079090412488723,
              text: "based on a pool of more than 80,000 students",
            },
            {
              x: 253,
              y: 755,
              w: 66,
              h: 18,
              confidence: 0.5918885988379238,
              text: "1ST YEAR",
            },
            {
              x: 452,
              y: 760,
              w: 94,
              h: 24,
              confidence: 0.9989059158650528,
              text: "SUCCESS",
            },
            {
              x: 661,
              y: 765,
              w: 110,
              h: 18,
              confidence: 0.7328744532703311,
              text: "TIME TO DEGREE",
            },
            {
              x: 810,
              y: 758,
              w: 426,
              h: 28,
              confidence: 0.839295883876756,
              text: "In addition, the study looked at five predictors of",
            },
            {
              x: 237,
              y: 775,
              w: 100,
              h: 16,
              confidence: 0.9977667278599476,
              text: "GRADUATE GPA",
            },
            {
              x: 808,
              y: 786,
              w: 324,
              h: 30,
              confidence: 0.7881748654013553,
              text: "success and eight criteria for success_",
            },
            {
              x: 1138,
              y: 784,
              w: 128,
              h: 30,
              confidence: 0.910822316818146,
              text: "The predictors",
            },
            {
              x: 804,
              y: 814,
              w: 472,
              h: 26,
              confidence: 0.7888928582379443,
              text: "included the three measures of the GRE General Test",
            },
            {
              x: 796,
              y: 840,
              w: 480,
              h: 32,
              confidence: 0.5449765524345253,
              text: "(verbal reasoning quantitative reasoning and analytical",
            },
            {
              x: 317,
              y: 885,
              w: 58,
              h: 16,
              confidence: 0.999254894907943,
              text: "OVERALL",
            },
            {
              x: 788,
              y: 870,
              w: 486,
              h: 30,
              confidence: 0.8418493637092006,
              text: "reasoning), GRE Subject Test scores and undergraduate",
            },
            {
              x: 623,
              y: 891,
              w: 58,
              h: 18,
              confidence: 0.9979370415298674,
              text: "FACULTY",
            },
            {
              x: 297,
              y: 903,
              w: 98,
              h: 16,
              confidence: 0.9834423630173099,
              text: "GRADUATE GPA",
            },
            {
              x: 623,
              y: 909,
              w: 58,
              h: 16,
              confidence: 0.9999588627987367,
              text: "RATINGS",
            },
            {
              x: 880,
              y: 900,
              w: 388,
              h: 31,
              confidence: 0.7156924137786553,
              text: "average (UGPA): The criteria for success are",
            },
            {
              x: 762,
              y: 928,
              w: 266,
              h: 28,
              confidence: 0.7545054646253319,
              text: "shown in the figure to the left",
            },
            {
              x: 471,
              y: 947,
              w: 56,
              h: 16,
              confidence: 0.9977274983060211,
              text: "DEGREE",
            },
            {
              x: 8,
              y: 958,
              w: 6,
              h: 28,
              confidence: 0.3760290170478733,
              text: "j",
            },
            {
              x: 457,
              y: 965,
              w: 84,
              h: 16,
              confidence: 0.9709981287195871,
              text: "ATTAINMENT",
            },
            {
              x: 734,
              y: 969,
              w: 542,
              h: 28,
              confidence: 0.9793459143728052,
              text: "Each of these criteria can be considered a different dimension",
            },
            {
              x: 8,
              y: 998,
              w: 6,
              h: 38,
              confidence: 0.2490307862000387,
              text: "1",
            },
            {
              x: 705,
              y: 995,
              w: 404,
              h: 36,
              confidence: 0.692906015950728,
              text: "of successful performance in graduate school.",
            },
            {
              x: 273,
              y: 1069,
              w: 430,
              h: 40,
              confidence: 0.7983044731505072,
              text: "Results of the Kuncel et al. study",
            },
            {
              x: 8,
              y: 1116,
              w: 6,
              h: 36,
              confidence: 0.11609389436797812,
              text: "1",
            },
            {
              x: 272,
              y: 1123,
              w: 340,
              h: 29,
              confidence: 0.951655631530451,
              text: "Results from this study show that:",
            },
            {
              x: 300,
              y: 1162,
              w: 232,
              h: 24,
              confidence: 0.6174315269856464,
              text: "The GRE General Test is a",
            },
            {
              x: 540,
              y: 1160,
              w: 268,
              h: 30,
              confidence: 0.97159738948307,
              text: "'generalizably valid predictor of",
            },
            {
              x: 884,
              y: 1158,
              w: 318,
              h: 32,
              confidence: 0.7947034493706381,
              text: "graduate GPA, overall graduate GPA,",
            },
            {
              x: 22,
              y: 1192,
              w: 8,
              h: 32,
              confidence: 0.4909094894968841,
              text: "1",
            },
            {
              x: 299,
              y: 1186,
              w: 653,
              h: 32,
              confidence: 0.7509362271412688,
              text: "comprehensive exam scores, publication citation counts and faculty ratings:",
            },
            {
              x: 7,
              y: 1227,
              w: 22,
              h: 20,
              confidence: 0.13280551135540009,
              text: "2 8",
            },
            {
              x: 299,
              y: 1223,
              w: 846,
              h: 37,
              confidence: 0.761433763150102,
              text: "The GRE General Test also correlates positively with degree attainment and research productivity:",
            },
            {
              x: 301,
              y: 1257,
              w: 944,
              h: 37,
              confidence: 0.6254878744146157,
              text: "The GRE General Test has better predictive validity than undergraduate grades or letters of recommendation:",
            },
            {
              x: 8,
              y: 1304,
              w: 6,
              h: 32,
              confidence: 0.23553165686786315,
              text: "1",
            },
            {
              x: 302,
              y: 1298,
              w: 964,
              h: 32,
              confidence: 0.7349711957425101,
              text: "The GRE Subject Tests are better predictors of success than either the GRE General Test or undergraduate GPA",
            },
            {
              x: 0,
              y: 1337,
              w: 33,
              h: 42,
              confidence: 0.4827325282477383,
              text: "Ji",
            },
            {
              x: 0,
              y: 1375,
              w: 17,
              h: 26,
              confidence: 0.6269895476885398,
              text: "87",
            },
            {
              x: 272,
              y: 1379,
              w: 962,
              h: 31,
              confidence: 0.8221927774515028,
              text: "This meta-analysis study is important because these results apply across a range of intended academic majors,",
            },
            {
              x: 271,
              y: 1404,
              w: 988,
              h: 37,
              confidence: 0.7802802208838472,
              text: "across native speakers of English and nonnative speakers of English; across traditional and nontraditional students",
            },
            {
              x: 0,
              y: 1419,
              w: 17,
              h: 50,
              confidence: 0.1270001093810471,
              text: "#",
            },
            {
              x: 272,
              y: 1436,
              w: 388,
              h: 29,
              confidence: 0.5852673838705659,
              text: "and across master's and doctoral programs.?",
            },
            {
              x: 295,
              y: 1573,
              w: 276,
              h: 20,
              confidence: 0.3042580492027992,
              text: "Kuncel,; N R, Hezlett; $. A and Ones; D. $. (2001).",
            },
            {
              x: 581,
              y: 1572,
              w: 695,
              h: 24,
              confidence: 0.7428211029554598,
              text: "comprehensive meta-analysis of the predictive validity of the Graduate Record Examinations: Implications for graduate student",
            },
            {
              x: 290,
              y: 1590,
              w: 370,
              h: 25,
              confidence: 0.6427124720326515,
              text: "selection and performarice: Psychological Bulletin, 127 (V), 162-181.",
            },
            {
              x: 297,
              y: 1611,
              w: 682,
              h: 21,
              confidence: 0.5541704435824318,
              text: "The master's analyses can be found in \"The Validity of the Graduate Record Examination for Master' s and Doctoral Programs:",
            },
            {
              x: 989,
              y: 1611,
              w: 274,
              h: 20,
              confidence: 0.5777656834343475,
              text: 'Meta-Analytic Investigation" by Kuncel, NR, Wee;',
            },
            {
              x: 309,
              y: 1631,
              w: 52,
              h: 18,
              confidence: 0.49703932472951295,
              text: "Serafin; S_",
            },
            {
              x: 365,
              y: 1633,
              w: 24,
              h: 14,
              confidence: 0.9999461098159776,
              text: "and",
            },
            {
              x: 386,
              y: 1628,
              w: 350,
              h: 24,
              confidence: 0.4779952712469071,
              text: "Hezlett; SA (In press) GRE Research Report: Princeton; NJ: ETS.",
            },
            {
              x: 369.1299778141514,
              y: 273.1289267866996,
              w: 72.7400443716972,
              h: 38.74214642660081,
              confidence: 0.5938871714379129,
              text: "thinking",
            },
            {
              x: 483.0220279500418,
              y: 459.1638810551212,
              w: 58.95594409991645,
              h: 34.67223788975764,
              confidence: 0.9999586375113546,
              text: "variety",
            },
            {
              x: 640.9909908090056,
              y: 461.1747742652155,
              w: 45.018018381988895,
              h: 33.65045146956902,
              confidence: 0.773813805522702,
              text: '(e.g"',
            },
            {
              x: 1044.9580569325292,
              y: 671.1867537178289,
              w: 45.08388613494162,
              h: 32.62649256434224,
              confidence: 0.9998682737350464,
              text: "from",
            },
            {
              x: 775.4100031799904,
              y: 902.4560050879847,
              w: 57.17999364001912,
              h: 21.0879898240305,
              confidence: 0.8327090230486973,
              text: "grade",
            },
            {
              x: 829.4789396203098,
              y: 901.4141973545267,
              w: 55.042120759380396,
              h: 22.171605290946673,
              confidence: 0.9999494067467012,
              text: "point",
            },
            {
              x: 807.0789916602317,
              y: 1157.1448741467184,
              w: 77.84201667953653,
              h: 36.71025170656321,
              confidence: 0.9699593145969541,
              text: "first-year",
            },
          ],
        },
      ],
      charts: [],
      items: [
        {
          type: "text",
          value: "ICMYK",
          md: "ICMYK",
          bBox: {
            x: -1,
            y: -37,
            w: 66,
            h: 37,
          },
        },
        {
          type: "heading",
          lvl: 1,
          value: "Comprehensive Review of Published GRE Validity Data",
          md: "# Comprehensive Review of Published GRE Validity Data",
          bBox: {
            x: 107,
            y: 31,
            w: 352,
            h: 242,
          },
        },
        {
          type: "text",
          value:
            "The Graduate Record Examinations (GRE) General Test measures skills that faculty and graduate deans have consistently said are essential to graduate school success. These skills of verbal reasoning, quantitative reasoning, critical thinking, and analytical writing are foundational skills for applicants to a U.S. graduate program, regardless of educational or linguistic background or country of origin.\n\nAlthough the GRE Program has many studies of the predictive validity of the GRE General Test (which are available on the GRE website: www.ets.org/gre), a recent meta-analysis by non-ETS researchers Nathan Kuncel, Sarah Hezlett, and Deniz Ones provides additional positive evidence of the relationship of the GRE General Test to various graduate school success. This meta-analysis is important because predictive validity studies are often difficult to conduct for a variety of reasons (e.g., insufficient data, test scores or predictors of success that do not vary greatly across examinees). Compared with earlier research, the Kuncel et al. meta-analysis improved on these studies by examining the validity of the GRE General Test for multiple disciplines using multiple measures of success, and by addressing statistical artifacts such as range restriction.",
          md: "The Graduate Record Examinations (GRE) General Test measures skills that faculty and graduate deans have consistently said are essential to graduate school success. These skills of verbal reasoning, quantitative reasoning, critical thinking, and analytical writing are foundational skills for applicants to a U.S. graduate program, regardless of educational or linguistic background or country of origin.\n\nAlthough the GRE Program has many studies of the predictive validity of the GRE General Test (which are available on the GRE website: www.ets.org/gre), a recent meta-analysis by non-ETS researchers Nathan Kuncel, Sarah Hezlett, and Deniz Ones provides additional positive evidence of the relationship of the GRE General Test to various graduate school success. This meta-analysis is important because predictive validity studies are often difficult to conduct for a variety of reasons (e.g., insufficient data, test scores or predictors of success that do not vary greatly across examinees). Compared with earlier research, the Kuncel et al. meta-analysis improved on these studies by examining the validity of the GRE General Test for multiple disciplines using multiple measures of success, and by addressing statistical artifacts such as range restriction.",
          bBox: {
            x: 94,
            y: 109,
            w: 483,
            h: 645,
          },
        },
        {
          type: "heading",
          lvl: 1,
          value: "Figure 1",
          md: "# Figure 1",
          bBox: {
            x: -30,
            y: 442,
            w: 30,
            h: 162,
          },
        },
        {
          type: "text",
          value: "Criteria for success",
          md: "Criteria for success",
          bBox: {
            x: 27,
            y: 254,
            w: 201,
            h: 86,
          },
        },
        {
          type: "table",
          rows: [
            ["COMPREHENSIVE RESEARCH", "EXAM SCORES", "PRODUCTIVITY"],
            ["1ST YEAR GRADUATE GPA", "SUCCESS", "TIME TO DEGREE"],
            ["OVERALL GRADUATE GPA", "FACULTY RATINGS", ""],
            ["DEGREE ATTAINMENT", "", ""],
          ],
          md: "| COMPREHENSIVE RESEARCH | EXAM SCORES     | PRODUCTIVITY   |\n| ---------------------- | --------------- | -------------- |\n| 1ST YEAR GRADUATE GPA  | SUCCESS         | TIME TO DEGREE |\n| OVERALL GRADUATE GPA   | FACULTY RATINGS |                |\n| DEGREE ATTAINMENT      |                 |                |",
          isPerfectTable: true,
          csv: '"COMPREHENSIVE RESEARCH","EXAM SCORES","PRODUCTIVITY"\n"1ST YEAR GRADUATE GPA","SUCCESS","TIME TO DEGREE"\n"OVERALL GRADUATE GPA","FACULTY RATINGS",""\n"DEGREE ATTAINMENT","",""',
          bBox: {
            x: -34,
            y: -37,
            w: 614,
            h: 793,
          },
        },
        {
          type: "text",
          value:
            "Each of these criteria can be considered a different dimension of successful performance in graduate school.",
          md: "Each of these criteria can be considered a different dimension of successful performance in graduate school.",
          bBox: {
            x: 183,
            y: 328,
            w: 396,
            h: 130,
          },
        },
        {
          type: "heading",
          lvl: 1,
          value: "Results of the Kuncel et al. study",
          md: "# Results of the Kuncel et al. study",
          bBox: {
            x: 97,
            y: 476,
            w: 207,
            h: 19,
          },
        },
        {
          type: "text",
          value:
            "1. The GRE General Test is a generalizably valid predictor of first-year graduate GPA, overall graduate GPA, comprehensive exam scores, publication citation counts, and faculty ratings.\n2. The GRE General Test also correlates positively with degree attainment and research productivity.\n3. The GRE General Test has better predictive validity than undergraduate grades or letters of recommendation.\n4. The GRE Subject Tests are better predictors of success than either the GRE General Test or undergraduate GPA.\n\nThis meta-analysis study is important because these results apply across a range of intended academic majors, across native speakers of English and nonnative speakers of English, across traditional and nontraditional students, and across master's and doctoral programs.\n\nKuncel, N. R., Hezlett, S. A., and Ones, D. J. (2001). Comprehensive meta-analysis of the predictive validity of the Graduate Record Examinations: Implications for graduate student selection and performance. Psychological Bulletin, 127(1), 162-181.\n\nThe master's analyses can be found in \"The Validity of the Graduate Record Examination for Master's and Doctoral Programs: Meta-Analytic Investigation\" by Kuncel, N. R., Wee, S., Serafin, S., Hezlett, S. A. (In press) GRE Research Report: Princeton, NJ: ETS.",
          md: "1. The GRE General Test is a generalizably valid predictor of first-year graduate GPA, overall graduate GPA, comprehensive exam scores, publication citation counts, and faculty ratings.\n2. The GRE General Test also correlates positively with degree attainment and research productivity.\n3. The GRE General Test has better predictive validity than undergraduate grades or letters of recommendation.\n4. The GRE Subject Tests are better predictors of success than either the GRE General Test or undergraduate GPA.\n\nThis meta-analysis study is important because these results apply across a range of intended academic majors, across native speakers of English and nonnative speakers of English, across traditional and nontraditional students, and across master's and doctoral programs.\n\nKuncel, N. R., Hezlett, S. A., and Ones, D. J. (2001). Comprehensive meta-analysis of the predictive validity of the Graduate Record Examinations: Implications for graduate student selection and performance. Psychological Bulletin, 127(1), 162-181.\n\nThe master's analyses can be found in \"The Validity of the Graduate Record Examination for Master's and Doctoral Programs: Meta-Analytic Investigation\" by Kuncel, N. R., Wee, S., Serafin, S., Hezlett, S. A. (In press) GRE Research Report: Princeton, NJ: ETS.",
          bBox: {
            x: -30,
            y: 261,
            w: 609,
            h: 493,
          },
        },
      ],
      status: "OK",
      originalOrientationAngle: 0,
      links: [],
      width: 613.73032,
      height: 793.306321,
      triggeredAutoMode: false,
      parsingMode: "accurate",
      structuredData: null,
      noStructuredContent: false,
      noTextContent: false,
      pageHeaderMarkdown: "\nICMYK\n",
      pageFooterMarkdown: "\n",
      confidence: 0.797,
    },
    {
      page: 2,
      text: "ICMYK\n\n\n         Validity of the Analytical Writing Measure\n         Because the Kuncel et al. meta-analysis was conducted before the Analytical Writing (AW) measure was\n         introduced into the GRE General Test, it may be useful to include validity information for this measure: The two\n         tasks that comprise the AW are both considered essential in many fields of graduate study: These two tasks are\n         complementary in that the first requires the writer to construct his/her own argument about an issue, and the\n         second requires a critique of someone else's argument by assessing its claims. For virtually all disciplines, AW adds\n         value to the GRE General Test because it provides unique information about test-taker abilities overᵃⁿᵈabove\n         skills measured in the Verbal and Quantitative measures_\n         Demonstrating the construct validity of the writing measure can be done by showing how AW correlates with other\n         measures it is intended to resemble As an illustration; AW correlates positively with other samples of academic\n         writing produced by examinees' as shown in the figure below: Examinees in this study were asked to provide two\n         writing samples: one representing their                             written work and one not quite as well written.\n                                              typical\n         This graph shows that there is\n         strong positive relationship                                                                                         Figure 2\n         between the GRE essay scores\n         and both of the writing samples                                     Relationship Between Mean GRE Writing Assessment Scores  Mean\n         from examinees: It should be                                        Undergraduate Course-Related Writing Sample    and\n         noted that the AW correlates\n         with these other indicators of\n         writing skill more closely than\n         does the personal statement          1\n         that many students submit with       J\n         their applications.\n\n j       Furthermore; data indicate that      1\n         AW has a low correlation (.21)\n         with the quantitative measure and    1\n         a moderate correlation (.60) with\n         the verbal measure  finding          8\n         that is consistent with the structure\n 1       and intent f those measures\n         Thus, AW is providing unique                                        1,5                     2.5    3.25            4.75      5.5\n         and valuable information beyond                                                                    GRE Essay Score Level\n\n 2 8     the multiple-choice GRE General                                     Your TypicalWritingSample              A Sample Not as Well Written\n         Test measures:\n\n         Summary\nJi       Because faculty want to make the best possible admissions decisions about graduate school applicants, it is\n         important to look objectively at the predictive value of the GRE General Test The Kuncel et al. study used all\n         existing data to arrive at the studys conclusions that the GRE General Test is a valid predictor of many criteria of\n        graduate school success. In addition, other research has demonstrated that the Analytical Writing section of the GRE\n         General Test can provide valuable information about applicants' abilities to produce analytical essays. For these\n         reasons; the GRE General Test is a valuable asset in the graduate admissions process.\n\n0         Powers, DE, Fowles, ME and Welsh, CK (1999) Further validation of  writing                 'graduate admissions GRE Research Report 96-13. Princeton; NJ: ETS\n                                                                                         assessment for\n          Powers; DE, and Fowles, ME (1997) The personal statement as an indicator of writing skill: cautionary note Educational Assessment; 4 (1), 75-87.\n         The correlation between the Verbal and Quantitative measures is ,36.",
      md: "\n\n# Validity of the Analytical Writing Measure\n\nBecause the Kuncel et al. meta-analysis was conducted before the Analytical Writing (AW) measure was introduced into the GRE General Test, it may be useful to include validity information for this measure: The two tasks that comprise the AW are both considered essential in many fields of graduate study: These two tasks are complementary in that the first requires the writer to construct his/her own argument about an issue, and the second requires a critique of someone else's argument by assessing its claims. For virtually all disciplines, AW adds value to the GRE General Test because it provides unique information about test-taker abilities over and above skills measured in the Verbal and Quantitative measures.\n\nDemonstrating the construct validity of the writing measure can be done by showing how AW correlates with other measures it is intended to resemble. As an illustration, AW correlates positively with other samples of academic writing produced by examinees, as shown in the figure below: Examinees in this study were asked to provide two writing samples: one representing their typical written work and one not quite as well written.\n\nThis graph shows that there is a strong positive relationship between the GRE essay scores and both of the writing samples from examinees: It should be noted that the AW correlates with these other indicators of writing skill more closely than does the personal statement that many students submit with their applications.\n\nFurthermore, data indicate that AW has a low correlation (.21) with the quantitative measure and a moderate correlation (.60) with the verbal measure, a finding that is consistent with the structure and intent of those measures. Thus, AW is providing unique and valuable information beyond the multiple-choice GRE General Test measures:\n\n| Relationship Between Mean GRE Writing Assessment Scores |                             |\n| ------------------------------------------------------- | --------------------------- |\n| Mean Undergraduate Course-Related Writing Sample        | Your Typical Writing Sample |\n| A Sample Not as Well Written                            |                             |\n| !Figure 2                                |                             |\n\n# Summary\n\nBecause faculty want to make the best possible admissions decisions about graduate school applicants, it is important to look objectively at the predictive value of the GRE General Test. The Kuncel et al. study used all existing data to arrive at the study's conclusions that the GRE General Test is a valid predictor of many criteria of graduate school success. In addition, other research has demonstrated that the Analytical Writing section of the GRE General Test can provide valuable information about applicants' abilities to produce analytical essays. For these reasons, the GRE General Test is a valuable asset in the graduate admissions process.\n\nPowers, DE, Fowles, ME and Welsh, CK (1999) Further validation of writing assessment for graduate admissions GRE Research Report 96-13. Princeton, NJ: ETS\n\nPowers, DE, and Fowles, ME (1997) The personal statement as an indicator of writing skill: cautionary note Educational Assessment; 4 (1), 75-87.\n\nThe correlation between the Verbal and Quantitative measures is .36.\n\n",
      images: [
        {
          name: "img_p1_1.png",
          height: 1800,
          width: 1424,
          x: -33.802700000000016,
          y: -36.97198000000003,
          original_width: 1424,
          original_height: 1800,
          ocr: [
            {
              x: 69,
              y: 0,
              w: 138,
              h: 43,
              confidence: 0.7704478411417865,
              text: "ICMYK",
            },
            {
              x: 144,
              y: 217,
              w: 540,
              h: 48,
              confidence: 0.841173175460519,
              text: "Validity of the Analytical Writing Measure",
            },
            {
              x: 148,
              y: 278,
              w: 904,
              h: 30,
              confidence: 0.6160596166710661,
              text: "Because the Kuncel et al. meta-analysis was conducted before the Analytical Writing (AW) measure was",
            },
            {
              x: 145,
              y: 307,
              w: 333,
              h: 25,
              confidence: 0.615496035818784,
              text: "introduced into the GRE General Test,",
            },
            {
              x: 482,
              y: 306,
              w: 632,
              h: 30,
              confidence: 0.6411974161107028,
              text: "it may be useful to include validity information for this measure: The two",
            },
            {
              x: 146,
              y: 332,
              w: 966,
              h: 33,
              confidence: 0.5801823148105139,
              text: "tasks that comprise the AW are both considered essential in many fields of graduate study: These two tasks are",
            },
            {
              x: 146,
              y: 362,
              w: 954,
              h: 33,
              confidence: 0.6996326392395993,
              text: "complementary in that the first requires the writer to construct his/her own argument about an issue, and the",
            },
            {
              x: 145,
              y: 387,
              w: 998,
              h: 36,
              confidence: 0.47011762201447754,
              text: "second requires a critique of someone else's argument by assessing its claims. For virtually all disciplines, AW adds",
            },
            {
              x: 145,
              y: 417,
              w: 867,
              h: 31,
              confidence: 0.7398494980395917,
              text: "value to the GRE General Test because it provides unique information about test-taker abilities over",
            },
            {
              x: 1050,
              y: 420,
              w: 60,
              h: 24,
              confidence: 0.9999984539514241,
              text: "above",
            },
            {
              x: 144,
              y: 446,
              w: 494,
              h: 28,
              confidence: 0.8402078906576201,
              text: "skills measured in the Verbal and Quantitative measures_",
            },
            {
              x: 148,
              y: 490,
              w: 996,
              h: 30,
              confidence: 0.5891657600979249,
              text: "Demonstrating the construct validity of the writing measure can be done by showing how AW correlates with other",
            },
            {
              x: 148,
              y: 518,
              w: 966,
              h: 30,
              confidence: 0.7382432358253431,
              text: "measures it is intended to resemble As an illustration; AW correlates positively with other samples of academic",
            },
            {
              x: 146,
              y: 545,
              w: 988,
              h: 31,
              confidence: 0.6742637847967758,
              text: "writing produced by examinees' as shown in the figure below: Examinees in this study were asked to provide two",
            },
            {
              x: 146,
              y: 576,
              w: 344,
              h: 30,
              confidence: 0.8790487351933165,
              text: "writing samples: one representing their",
            },
            {
              x: 548,
              y: 576,
              w: 410,
              h: 28,
              confidence: 0.6505968180385592,
              text: "written work and one not quite as well written.",
            },
            {
              x: 146,
              y: 620,
              w: 266,
              h: 28,
              confidence: 0.7724502511958939,
              text: "This graph shows that there is",
            },
            {
              x: 160,
              y: 645,
              w: 240,
              h: 31,
              confidence: 0.8720603077566232,
              text: "strong positive relationship",
            },
            {
              x: 1157,
              y: 663,
              w: 54,
              h: 18,
              confidence: 0.9370852600294692,
              text: "Figure 2",
            },
            {
              x: 146,
              y: 676,
              w: 274,
              h: 28,
              confidence: 0.9303922429851829,
              text: "between the GRE essay scores",
            },
            {
              x: 146,
              y: 700,
              w: 282,
              h: 32,
              confidence: 0.8324635788099704,
              text: "and both of the writing samples",
            },
            {
              x: 542,
              y: 708,
              w: 532,
              h: 26,
              confidence: 0.7130555988507787,
              text: "Relationship Between Mean GRE Writing Assessment Scores",
            },
            {
              x: 1110,
              y: 706,
              w: 57,
              h: 27,
              confidence: 0.9999996423721313,
              text: "Mean",
            },
            {
              x: 146,
              y: 732,
              w: 260,
              h: 26,
              confidence: 0.6976198303043074,
              text: "from examinees: It should be",
            },
            {
              x: 646,
              y: 726,
              w: 414,
              h: 30,
              confidence: 0.8982895944574623,
              text: "Undergraduate Course-Related Writing Sample",
            },
            {
              x: 146,
              y: 760,
              w: 254,
              h: 26,
              confidence: 0.7346884931077191,
              text: "noted that the AW correlates",
            },
            {
              x: 146,
              y: 788,
              w: 260,
              h: 26,
              confidence: 0.989492821483032,
              text: "with these other indicators of",
            },
            {
              x: 146,
              y: 815,
              w: 260,
              h: 31,
              confidence: 0.6280785496085044,
              text: "writing skill more closely than",
            },
            {
              x: 146,
              y: 844,
              w: 256,
              h: 28,
              confidence: 0.9994691573708969,
              text: "does the personal statement",
            },
            {
              x: 146,
              y: 872,
              w: 280,
              h: 30,
              confidence: 0.9334332443575516,
              text: "that many students submit with",
            },
            {
              x: 495,
              y: 849,
              w: 16,
              h: 44,
              confidence: 0.6255662623740967,
              text: "1",
            },
            {
              x: 146,
              y: 900,
              w: 154,
              h: 30,
              confidence: 0.6580834783490692,
              text: "their applications.",
            },
            {
              x: 494,
              y: 890,
              w: 20,
              h: 61,
              confidence: 0.10594286567894873,
              text: "J",
            },
            {
              x: 145,
              y: 942,
              w: 275,
              h: 28,
              confidence: 0.7457253209182033,
              text: "Furthermore; data indicate that",
            },
            {
              x: 8,
              y: 958,
              w: 6,
              h: 28,
              confidence: 0.3760290170478733,
              text: "j",
            },
            {
              x: 148,
              y: 972,
              w: 268,
              h: 26,
              confidence: 0.5737977534415069,
              text: "AW has a low correlation (.21)",
            },
            {
              x: 146,
              y: 997,
              w: 302,
              h: 31,
              confidence: 0.9539269083870665,
              text: "with the quantitative measure and",
            },
            {
              x: 148,
              y: 1027,
              w: 294,
              h: 27,
              confidence: 0.8816250161519767,
              text: "a moderate correlation (.60) with",
            },
            {
              x: 495,
              y: 1007,
              w: 16,
              h: 58,
              confidence: 0.4023880524815837,
              text: "1",
            },
            {
              x: 146,
              y: 1054,
              w: 174,
              h: 29,
              confidence: 0.9687930937733199,
              text: "the verbal measure",
            },
            {
              x: 146,
              y: 1084,
              w: 308,
              h: 26,
              confidence: 0.8084704141728555,
              text: "that is consistent with the structure",
            },
            {
              x: 495,
              y: 1067,
              w: 16,
              h: 56,
              confidence: 0.3972460636277084,
              text: "8",
            },
            {
              x: 8,
              y: 1116,
              w: 6,
              h: 36,
              confidence: 0.11609389436797812,
              text: "1",
            },
            {
              x: 146,
              y: 1112,
              w: 262,
              h: 26,
              confidence: 0.8338940041257389,
              text: "and intent f those measures",
            },
            {
              x: 146,
              y: 1138,
              w: 258,
              h: 32,
              confidence: 0.8825012947964797,
              text: "Thus, AW is providing unique",
            },
            {
              x: 597,
              y: 1149,
              w: 22,
              h: 14,
              confidence: 0.5298607349395752,
              text: "1,5",
            },
            {
              x: 699,
              y: 1149,
              w: 22,
              h: 16,
              confidence: 0.9985455145232435,
              text: "2.5",
            },
            {
              x: 795,
              y: 1149,
              w: 32,
              h: 16,
              confidence: 0.849518895149231,
              text: "3.25",
            },
            {
              x: 1001,
              y: 1149,
              w: 30,
              h: 16,
              confidence: 0.997567355632782,
              text: "4.75",
            },
            {
              x: 1107,
              y: 1149,
              w: 22,
              h: 16,
              confidence: 0.8885402679443359,
              text: "5.5",
            },
            {
              x: 146,
              y: 1167,
              w: 292,
              h: 30,
              confidence: 0.7763658646871066,
              text: "and valuable information beyond",
            },
            {
              x: 771,
              y: 1173,
              w: 180,
              h: 20,
              confidence: 0.836406295437837,
              text: "GRE Essay Score Level",
            },
            {
              x: 146,
              y: 1196,
              w: 292,
              h: 28,
              confidence: 0.8630288960937932,
              text: "the multiple-choice GRE General",
            },
            {
              x: 604,
              y: 1206,
              w: 92,
              h: 24,
              confidence: 0.952091802164754,
              text: "Your Typical",
            },
            {
              x: 751,
              y: 1207,
              w: 58,
              h: 20,
              confidence: 0.9999972746478,
              text: "Sample",
            },
            {
              x: 940,
              y: 1204,
              w: 218,
              h: 25,
              confidence: 0.7051005795953474,
              text: "A Sample Not as Well Written",
            },
            {
              x: 7,
              y: 1227,
              w: 22,
              h: 20,
              confidence: 0.13280551135540009,
              text: "2 8",
            },
            {
              x: 148,
              y: 1226,
              w: 130,
              h: 24,
              confidence: 0.8766476339040201,
              text: "Test measures:",
            },
            {
              x: 145,
              y: 1292,
              w: 135,
              h: 41,
              confidence: 0.9302236912345236,
              text: "Summary",
            },
            {
              x: 0,
              y: 1337,
              w: 33,
              h: 42,
              confidence: 0.4827325282477383,
              text: "Ji",
            },
            {
              x: 148,
              y: 1345,
              w: 898,
              h: 33,
              confidence: 0.6687947536116253,
              text: "Because faculty want to make the best possible admissions decisions about graduate school applicants,",
            },
            {
              x: 1050,
              y: 1350,
              w: 34,
              h: 24,
              confidence: 0.9938967706998282,
              text: "it is",
            },
            {
              x: 146,
              y: 1374,
              w: 944,
              h: 30,
              confidence: 0.46533098899315756,
              text: "important to look objectively at the predictive value of the GRE General Test The Kuncel et al. study used all",
            },
            {
              x: 146,
              y: 1402,
              w: 974,
              h: 32,
              confidence: 0.863010322178315,
              text: "existing data to arrive at the studys conclusions that the GRE General Test is a valid predictor of many criteria of",
            },
            {
              x: 144,
              y: 1430,
              w: 1008,
              h: 32,
              confidence: 0.53257167910514,
              text: "graduate school success. In addition, other research has demonstrated that the Analytical Writing section of the GRE",
            },
            {
              x: 146,
              y: 1460,
              w: 964,
              h: 31,
              confidence: 0.4976422299166554,
              text: "General Test can provide valuable information about applicants' abilities to produce analytical essays. For these",
            },
            {
              x: 146,
              y: 1486,
              w: 746,
              h: 32,
              confidence: 0.5861275186523822,
              text: "reasons; the GRE General Test is a valuable asset in the graduate admissions process.",
            },
            {
              x: 6,
              y: 1554,
              w: 8,
              h: 22,
              confidence: 0.19911485108716764,
              text: "0",
            },
            {
              x: 166,
              y: 1575,
              w: 387,
              h: 20,
              confidence: 0.7332884350539466,
              text: "Powers, DE, Fowles, ME and Welsh, CK (1999) Further validation of",
            },
            {
              x: 601,
              y: 1577,
              w: 86,
              h: 16,
              confidence: 0.9998354949191914,
              text: "assessment for",
            },
            {
              x: 682,
              y: 1573,
              w: 388,
              h: 25,
              confidence: 0.6635915544230965,
              text: "'graduate admissions GRE Research Report 96-13. Princeton; NJ: ETS",
            },
            {
              x: 167,
              y: 1594,
              w: 506,
              h: 21,
              confidence: 0.4804123272924798,
              text: "Powers; DE, and Fowles, ME (1997) The personal statement as an indicator of writing skill:",
            },
            {
              x: 683,
              y: 1595,
              w: 298,
              h: 18,
              confidence: 0.2407010778693426,
              text: "cautionary note Educational Assessment; 4 (1), 75-87.",
            },
            {
              x: 165,
              y: 1615,
              w: 376,
              h: 18,
              confidence: 0.5072341115482678,
              text: "The correlation between the Verbal and Quantitative measures is ,36.",
            },
            {
              x: 1010.9859597468732,
              y: 422.2761315696845,
              w: 39.02808050625356,
              h: 20.44773686063104,
              confidence: 0.9999877490683106,
              text: "and",
            },
            {
              x: 486.5430712064641,
              y: 578.3775281716354,
              w: 64.91385758707179,
              h: 23.24494365672922,
              confidence: 0.7768280242211475,
              text: "typical",
            },
            {
              x: 1072.8905996075496,
              y: 710.3358994113244,
              w: 39.21880078490085,
              h: 18.328201177351275,
              confidence: 0.9999671014761352,
              text: "and",
            },
            {
              x: 497.6484187230327,
              y: 948.031144848983,
              w: 9.70316255393459,
              h: 59.93771030203402,
              confidence: 0.5820606930861949,
              text: "1",
            },
            {
              x: 357.1051750205922,
              y: 1050.1365600658949,
              w: 62.78964995881563,
              h: 37.72687986821029,
              confidence: 0.7872239117474585,
              text: "finding",
            },
            {
              x: 695.2572186472918,
              y: 1202.1430466182294,
              w: 54.48556270541644,
              h: 28.713906763541218,
              confidence: 0.9999616563609127,
              text: "Writing",
            },
            {
              x: 561.202547777171,
              y: 1572.1658598874935,
              w: 40.5949044456579,
              h: 26.66828022501295,
              confidence: 0.5255717235525993,
              text: "writing ",
            },
          ],
        },
      ],
      charts: [],
      items: [
        {
          type: "heading",
          lvl: 1,
          value: "Validity of the Analytical Writing Measure",
          md: "# Validity of the Analytical Writing Measure",
          bBox: {
            x: 35,
            y: 67,
            w: 259,
            h: 664,
          },
        },
        {
          type: "text",
          value:
            "Because the Kuncel et al. meta-analysis was conducted before the Analytical Writing (AW) measure was introduced into the GRE General Test, it may be useful to include validity information for this measure: The two tasks that comprise the AW are both considered essential in many fields of graduate study: These two tasks are complementary in that the first requires the writer to construct his/her own argument about an issue, and the second requires a critique of someone else's argument by assessing its claims. For virtually all disciplines, AW adds value to the GRE General Test because it provides unique information about test-taker abilities over and above skills measured in the Verbal and Quantitative measures.\n\nDemonstrating the construct validity of the writing measure can be done by showing how AW correlates with other measures it is intended to resemble. As an illustration, AW correlates positively with other samples of academic writing produced by examinees, as shown in the figure below: Examinees in this study were asked to provide two writing samples: one representing their typical written work and one not quite as well written.\n\nThis graph shows that there is a strong positive relationship between the GRE essay scores and both of the writing samples from examinees: It should be noted that the AW correlates with these other indicators of writing skill more closely than does the personal statement that many students submit with their applications.\n\nFurthermore, data indicate that AW has a low correlation (.21) with the quantitative measure and a moderate correlation (.60) with the verbal measure, a finding that is consistent with the structure and intent of those measures. Thus, AW is providing unique and valuable information beyond the multiple-choice GRE General Test measures:",
          md: "Because the Kuncel et al. meta-analysis was conducted before the Analytical Writing (AW) measure was introduced into the GRE General Test, it may be useful to include validity information for this measure: The two tasks that comprise the AW are both considered essential in many fields of graduate study: These two tasks are complementary in that the first requires the writer to construct his/her own argument about an issue, and the second requires a critique of someone else's argument by assessing its claims. For virtually all disciplines, AW adds value to the GRE General Test because it provides unique information about test-taker abilities over and above skills measured in the Verbal and Quantitative measures.\n\nDemonstrating the construct validity of the writing measure can be done by showing how AW correlates with other measures it is intended to resemble. As an illustration, AW correlates positively with other samples of academic writing produced by examinees, as shown in the figure below: Examinees in this study were asked to provide two writing samples: one representing their typical written work and one not quite as well written.\n\nThis graph shows that there is a strong positive relationship between the GRE essay scores and both of the writing samples from examinees: It should be noted that the AW correlates with these other indicators of writing skill more closely than does the personal statement that many students submit with their applications.\n\nFurthermore, data indicate that AW has a low correlation (.21) with the quantitative measure and a moderate correlation (.60) with the verbal measure, a finding that is consistent with the structure and intent of those measures. Thus, AW is providing unique and valuable information beyond the multiple-choice GRE General Test measures:",
          bBox: {
            x: -31,
            y: 96,
            w: 546,
            h: 635,
          },
        },
        {
          type: "table",
          rows: [
            ["Relationship Between Mean GRE Writing Assessment Scores", ""],
            [
              "Mean Undergraduate Course-Related Writing Sample",
              "Your Typical Writing Sample",
            ],
            ["A Sample Not as Well Written", ""],
            ["!Figure 2", ""],
          ],
          md: "| Relationship Between Mean GRE Writing Assessment Scores |                             |\n| ------------------------------------------------------- | --------------------------- |\n| Mean Undergraduate Course-Related Writing Sample        | Your Typical Writing Sample |\n| A Sample Not as Well Written                            |                             |\n| !Figure 2                                               |                             |",
          isPerfectTable: false,
          csv: '"Relationship Between Mean GRE Writing Assessment Scores",""\n"Mean Undergraduate Course-Related Writing Sample","Your Typical Writing Sample"\n"A Sample Not as Well Written",""\n"!Figure 2",""',
          bBox: {
            x: -34,
            y: -37,
            w: 582,
            h: 784,
          },
        },
        {
          type: "heading",
          lvl: 1,
          value: "Summary",
          md: "# Summary",
          bBox: {
            x: 36,
            y: 583,
            w: 65,
            h: 20,
          },
        },
        {
          type: "text",
          value:
            "Because faculty want to make the best possible admissions decisions about graduate school applicants, it is important to look objectively at the predictive value of the GRE General Test. The Kuncel et al. study used all existing data to arrive at the study's conclusions that the GRE General Test is a valid predictor of many criteria of graduate school success. In addition, other research has demonstrated that the Analytical Writing section of the GRE General Test can provide valuable information about applicants' abilities to produce analytical essays. For these reasons, the GRE General Test is a valuable asset in the graduate admissions process.\n\nPowers, DE, Fowles, ME and Welsh, CK (1999) Further validation of writing assessment for graduate admissions GRE Research Report 96-13. Princeton, NJ: ETS\n\nPowers, DE, and Fowles, ME (1997) The personal statement as an indicator of writing skill: cautionary note Educational Assessment; 4 (1), 75-87.\n\nThe correlation between the Verbal and Quantitative measures is .36.",
          md: "Because faculty want to make the best possible admissions decisions about graduate school applicants, it is important to look objectively at the predictive value of the GRE General Test. The Kuncel et al. study used all existing data to arrive at the study's conclusions that the GRE General Test is a valid predictor of many criteria of graduate school success. In addition, other research has demonstrated that the Analytical Writing section of the GRE General Test can provide valuable information about applicants' abilities to produce analytical essays. For these reasons, the GRE General Test is a valuable asset in the graduate admissions process.\n\nPowers, DE, Fowles, ME and Welsh, CK (1999) Further validation of writing assessment for graduate admissions GRE Research Report 96-13. Princeton, NJ: ETS\n\nPowers, DE, and Fowles, ME (1997) The personal statement as an indicator of writing skill: cautionary note Educational Assessment; 4 (1), 75-87.\n\nThe correlation between the Verbal and Quantitative measures is .36.",
          bBox: {
            x: -30,
            y: 302,
            w: 556,
            h: 436,
          },
        },
      ],
      status: "OK",
      originalOrientationAngle: 0,
      links: [],
      width: 613.73032,
      height: 793.306321,
      triggeredAutoMode: false,
      parsingMode: "accurate",
      structuredData: null,
      noStructuredContent: false,
      noTextContent: false,
      pageHeaderMarkdown: "",
      pageFooterMarkdown: "",
      confidence: 0.961,
    },
  ],
  job_metadata: {
    credits_used: 0,
    job_credits_usage: 0,
    job_pages: 2,
    job_auto_mode_triggered_pages: 0,
    job_is_cache_hit: false,
  },
};
